environment: development
name: rpa-mit-invoice
namespace: ffc-rpa
workstream: ffc-rpa
image: rpa-mit-invoice

labels: {}

azureIdentity:
  resourceID: dummy
  clientID: dummy

appInsights:
  connectionString:

containerConfigMap:
  name: rpa-mit-invoice-config-map

containerSecret:
  name: rpa-mit-invoice-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  comPlusEnableDiagnostics: 0

volumeMounts:
  mountPath: /var/www/
  name: core-app-dir

aadPodIdentity: true