version: '3.8'

services:
  rpa-mit-invoice:
    build:
      target: development
    image: rpa-mit-invoice
    container_name: rpa-mit-invoice-test
    entrypoint: dotnet test ./EST.MIT.Invoice.Api.Test/EST.MIT.Invoice.Api.Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./test-output/'
    volumes:
      - ./test-output:/home/dotnet/EST.MIT.Invoice.Api.Tests/test-output
