version: '3.8'

services:
  rpa-mit-invoice:
    build:
      context: .
      target: production
    image: rpa-mit-invoice
    container_name: rpa-mit-invoice
    ports:
      - 3000:3000
    networks:
      - mit
    environment:
      COMPlus_EnableDiagnostics: 0
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_DB: rpa_mit_invoices
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASS:-password}
      POSTGRES_PORT: "5432"
      SCHEMA_DEFAULT: ${POSTGRES_SCHEMA_NAME:-public}
      AzureWebJobsStorage: ${AzureWebJobsStorage} 
      QueueConnectionString: ${QueueConnectionString}
      PaymentQueueName: ${PaymentQueueName}
      EventQueueName: ${EventQueueName}
      AzureADPostgreSQLResourceID: https://ossrdbms-aad.database.windows.net/.default
      ReferenceDataAPIBaseURI: ${ReferenceDataAPIBaseURI:-https://localhost:7012} 
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Development}