version: '3.8'

services:
  rpa-mit-invoice:
    build:
      context: .
      target: production
    image: rpa-mit-invoice
    container_name: rpa-mit-invoice
    environment:
      COMPlus_EnableDiagnostics: 0
