{{- define "rpa-mit-invoice" -}}
ports:
- containerPort: {{ .Values.container.port }}
volumeMounts:
- mountPath: {{ .Values.volumeMounts.mountPath }}
  name: {{ .Values.volumeMounts.name }}
{{- end -}}