environment: development
name: rpa-mit-invoice
namespace: ffc-rpa
workstream: ffc-rpa
image: rpa-mit-invoice

labels: {}

azureIdentity:
  resourceID: dummy
  clientID: dummy

appInsights:
  connectionString:

containerConfigMap:
  name: rpa-mit-invoice-config-map

containerSecret:
  name: rpa-mit-invoice-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: low
  replicas: 1
  minReadySeconds: 5
  imagePullSecret:

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 120Mi
  requestCpu: 5m
  limitMemory: 120Mi
  limitCpu: 120m
  port: 3000
  comPlusEnableDiagnostics: 0
  AzureADPostgreSQLResourceID: https://ossrdbms-aad.database.windows.net/.default
  ReferenceDataAPIBaseURI: from-config
  serviceBusConnectionString__fullyQualifiedNamespace: value-from-app-config-service
  serviceBusConnectionString__credential: value-from-app-config-service
  serviceBusQueueName: value-from-app-config-service
  queueConnectionString__credential: value-from-app-config-service
  queueConnectionString__queueServiceUri: value-from-app-config-service
  eventQueueName: value-from-app-config-service
  paymentQueueName: value-from-app-config-service

ingress:
  class: nginx
  endpoint: rpa-mit-invoice
  server: value.replaced.from.app.config

postgresService:
  postgresDb: rpa_mit_invoice
  # postgresExternalName is the external host name to which PostgreSQL
  # requests should be forwarded. If empty, PostgreSQL is assumed to be
  # within the cluster and accessible via postgresHost
  postgresExternalName: sndffcdbssq1002.postgres.database.azure.com
  postgresHost: rpa-mit-invoice-postgres
  postgresPort: 5432
  postgresSchema: public
  postgresUser: postgres
  postgresPassword: password

volumeMounts:
  mountPath: /var/www/
  name: core-app-dir

aadPodIdentity: true