{{- include "ffc-helm-library.container-config-map" (list . "rpa-mit-invoice.config-map") -}}
{{- define "rpa-mit-invoice.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ .Values.container.comPlusEnableDiagnostics | quote }}
  PORT: {{ .Values.container.port | quote }}
{{- end -}}