{{- include "ffc-helm-library.container-config-map" (list . "rpa-mit-invoice.config-map") -}}
{{- define "rpa-mit-invoice.config-map" -}}
data:
  COMPlus_EnableDiagnostics: {{ .Values.container.comPlusEnableDiagnostics | quote }}
  PORT: {{ .Values.container.port | quote }}
  POSTGRES_HOST: {{ .Values.postgresService.postgresHost | quote }}
  POSTGRES_DB: {{ .Values.postgresService.postgresDb | quote }}
  POSTGRES_USER: {{ .Values.postgresService.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresService.postgresPassword | quote }}
  POSTGRES_PORT: {{ .Values.postgresService.postgresPort | quote }}
  AzureADPostgreSQLResourceID: {{ .Values.container.AzureADPostgreSQLResourceID | quote }}
{{- end -}}